development:
  adapter: postgresql
  encoding: unicode
  database: bdd_dev
  pool: 5
  username: postgres
  password: postgres
  template: template0
  host: localhost

test: &test
  adapter: postgresql
  encoding: unicode
  database: bdd_test
  pool: 5
  username: postgres
  password: postgres
  template: template0
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: bdd_production
  pool: 5
  username: postgres
  password: postgres
  template: template0
  host: localhost
cucumber:
  <<: *test